#! /usr/bin/env python3

import socket
import argparse

parser = argparse.ArgumentParser()

parser.add_argument(
    "-s",
    "--serverhost",
    type=str,
    default="127.0.0.1",
    help="The server host address. Must be IPV4"
)
parser.add_argument(
    "-p",
    "--port",
    type=int,
    default=7890,
    help= "server port number"
)

args = parser.parse_args()

HOST: str = args.serverhost
PORT: int = args.port

print(f"HOST: {HOST}, PORT: {PORT}")

with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
    sock.sendto(bytes("", "utf-8"), (HOST, PORT))
    data, _ = sock.recvfrom(32)
    print("timestamp returned: {}".format(int.from_bytes(data, "little")))
